AllCops:
  Exclude:
    - db/schema.rb

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - db/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Rails/HasAndBelongsToMany:
  Enabled: False

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NestedParenthesizedCalls:
  Enabled: false
