AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - db/**/*.rb

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: False

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NestedParenthesizedCalls:
  Enabled: false
