language: ruby

services:
  - docker

install: true

before_script:
  - docker build -t openwebslides .

script:
  - docker run --rm openwebslides bash -c "bundle exec rails db:prepare RAILS_ENV=test && bundle exec rspec"
