language: ruby

services:
  - docker

install: true

cache: yarn

before_script:
  - docker build -t openwebslides .

script:
  - docker run --rm openwebslides bash -c "bundle exec rails db:prepare RAILS_ENV=test && bundle exec rspec"
  - docker run --rm openwebslides bash -c "yarn test"
