language: ruby
rvm:
  - 2.4.1
cache: bundler
env:
  - RAILS_ENV=test CI=true TRAVIS=true
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rails db:sample
script:
  - bundle exec rspec
