language: ruby

services:
  - docker

install: true

before_script:
  - docker-compose build

script:
  - docker-compose run --rm app bash -c "bundle exec rails db:setup RAILS_ENV=test && bundle exec rspec"
