version: '2'

services:

  app:
    build: .
    env_file:
      - openwebslides.env
    volumes:
      - public:/app/public
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'openwebslides'
      POSTGRES_PASSWORD: 'openwebslides'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  public: {}
  postgres:
