export const samples = [
  {
    id: 'ertwc2',
    timestamp: '1000',
    type: 'deck_created',
    targetDeck: 'OpenWebSlides',
    concernedUser: 'Florian',
    viewed: false,
  },
  {
    id: '5u7g5t',
    timestamp: '1001',
    type: 'deck_created',
    targetDeck: 'World Domination',
    concernedUser: 'Rein',
    viewed: true,
  },
  {
    id: '2341d',
    timestamp: '1002',
    type: 'deck_created',
    targetDeck: 'The greatest deck ever. Bigly.',
    concernedUser: 'Donald Trump',
    viewed: true,
  },
  {
    id: '6h245',
    timestamp: '1003',
    type: 'deck_updated',
    targetDeck: 'How to always be on time',
    concernedUser: 'Gandalf',
    viewed: false,
  },
  {
    id: 'ew2345',
    timestamp: '1004',
    type: 'deck_created',
    targetDeck: 'ts ard to rwtie with onw hnd',
    concernedUser: 'Jamie Lannister ',
    viewed: false,
  },
  {
    id: '234rw',
    timestamp: '1005',
    type: 'deck_updated',
    targetDeck: 'You shall not use html tables for a list',
    concernedUser: 'Min',
    viewed: true,
  },
  {
    id: '2345rqwd',
    timestamp: '1006',
    type: 'deck_created',
    targetDeck:
      "Hey! I'm making a deck! Funny how deck almost sounds like [censured]. Wait, seriously, I can't write" +
        "[censured]? What kind of lame-[censured] app is this? I bet you that the developpers are all dorks. And that they don't have friends. " +
        "And that they're mad at me because this title is way to long now. Hah! [censored] you developers!",
    concernedUser: 'Deadpool',
    viewed: false,
  },
  {
    id: 'ef23',
    timestamp: '1007',
    type: 'deck_updated',
    targetDeck: 'How to come up with funny deck names',
    concernedUser: 'Luca',
    viewed: true,
  },
  {
    id: '2345',
    timestamp: '1008',
    type: 'deck_created',
    targetDeck: 'The way of the Jedi',
    concernedUser: 'Obi-Wan',
    viewed: true,
  },
  {
    id: 'r43',
    timestamp: '1009',
    type: 'deck_created',
    targetDeck: 'Let it go',
    concernedUser: 'The frozen chick',
    viewed: false,
  },
  {
    id: '234',
    timestamp: '1010',
    type: 'deck_updated',
    targetDeck: 'I should really write a generator for deck names',
    concernedUser: 'Luca Dorigo',
    viewed: true,
  },
];

export default samples;
