export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USER_DECKS_IDS_SUCCESS = 'FETCH_USER_DECKS_IDS_SUCCESS';

export const FETCH_USER_COLLABORATIONS_SUCCESS = 'FETCH_USER_COLLABORATIONS_SUCCESS';
