default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: openwebslides
  password: openwebslides
  host: postgres

development:
  <<: *default
  database: openwebslides_development

test:
  <<: *default
  database: openwebslides_test

production:
  <<: *default
  database: openwebslides_production
  username: openwebslides
  password: <%= ENV['OPENWEBSLIDES_DATABASE_PASSWORD'] %>
