##
# Repository path
#
# Local path used for persistent repository storage
repository_path: /srv/openwebslides/repositories

##
# Repository seed
#
# URL to git repository that will be used as starting point for new repositories
repository_seed: https://github.com/OpenWebslides/EmptySlidedeck.git

provider:
  ##
  # Data provider type
  #
  # Possible values: ssh, github, local
  #
  # SSH Provider synchronizes the repositories to an external SSH server.
  # GitHub provider synchronizes the repositories to a GitHub organization
  # Local provider does nothing (the repositories are stored locally anyhow)
  #
  type: ssh

  ##
  # Provider hostname/IP
  #
  host: localhost

  ##
  # Provider port
  #
  # Defaults to 22 for ssh provider and 80 for github
  port: 22

  ##
  # Path to repository store/organisation
  #
  #
  # Possible values: a remote path (for ssh provider), organisation name (for github provider)
  path: /srv/openwebslides/repositories

  ##
  # GitHub OAuth2 credentials (only for github provider)
  #
  # github_id: <%= ENV['OAUTH_GITHUB_ID'] %>
  # github_secret: <%= ENV['OAUTH_GITHUB_SECRET'] %>

  ##
  # User (only for ssh provider)
  #
  user: openwebslides

  ##
  #
  # Password for user
  #
  # password: openwebslides

  ##
  # Path to private keyfile (only for ssh provider)
  #
  private_key: <%= Rails.root.join 'config', 'private.key' %>
