##
# Repository path
#
# Local path used for persistent repository storage
repository_path: <%= Rails.root.join 'data' %>

##
# Template path
#
# Local path used for templates
template_path: <%= Rails.root.join 'lib', 'assets', 'templates' %>

oauth2:
  ##
  # GitHub OAuth2 credentials
  #
  github_id: <%= ENV['OAUTH_GITHUB_ID'] %>
  github_secret: <%= ENV['OAUTH_GITHUB_SECRET'] %>

  ##
  # Google OAuth2 credentials
  #
  google_id: <%= ENV['OAUTH_GOOGLE_ID'] %>
  google_secret: <%= ENV['OAUTH_GOOGLE_SECRET'] %>

  ##
  # Facebook OAuth2 credentials
  #
  facebook_id: <%= ENV['OAUTH_FACEBOOK_ID'] %>
  facebook_secret: <%= ENV['OAUTH_FACEBOOK_SECRET'] %>

api:
  ##
  # Access token lifetime (in hours)
  #
  token_lifetime: 24

  ##
  # Asset signed URL lifetime (in hours)
  #
  asset_url_lifetime: 5

##
# Default template for new decks
#
default_template: shower-ows

##
# GitHub backend store configuration
#
github:
  ##
  # Enable syncing to GitHub
  #
  enabled: false

  ##
  # GitHub hostname
  #
  host: github.com

  ##
  # GitHub SSH username (usually 'git')
  #
  ssh_user: git

  ##
  # GitHub organization
  #
  organization: <%= ENV['GITHUB_ORGANIZATION'] %>

  ##
  # Path to private key
  #
  private_key: <%= Rails.root.join 'config', 'openwebslides.pem' %>

  ##
  # Passphrase for private key
  #
  # passphrase: <%= ENV['KEYFILE_PASSPHRASE'] %>

  ##
  # GitHub machine user, must be admin of GitHub organization
  #
  github_user: <%= ENV['GITHUB_MACHINE_USER'] %>

  ##
  # GitHub machine user passphrase
  #
  github_passphrase: <%= ENV['GITHUB_MACHINE_PASSWORD'] %>

  ##
  # GitHub API endpoint
  #
  # https://api.github.com/ for GitHub
  # https://myhost.com/api/v3/ for GitHub Enterprise
  #
  github_api: https://api.github.com/
