##
# Repository path
#
# Local path used for persistent repository storage
repository_path: /srv/repositories

provider:
  ##
  # Data provider type
  #
  # Possible values: ssh, github, local
  #
  # SSH Provider synchronizes the repositories to an external SSH server.
  # GitHub provider synchronizes the repositories to a GitHub organization
  # Local provider does nothing (the repositories are stored locally anyhow)
  #
  type: github

  ##
  # PROVIDER COMMON CONFIGURATION
  #

  ##
  # Provider hostname/IP
  #
  # Hostname of SSH server (for both providers)
  #
  host: github.com


  ##
  # Provider user
  #
  # Login user (for ssh provider)
  # GitHub username (for github provider)
  #
  user: openwebslides


  ##
  # Path to repository store/organisation
  #
  #
  # Remote path (for ssh provider)
  # Organization name (for github provider)
  #
  path: openwebslides

  ##
  # SSH PROVIDER CONFIGURATION
  #

  ##
  # Path to public keyfile
  #
  public_key: <%= Rails.root.join 'config', 'id_rsa.pub' %>

  ##
  # Path to private keyfile
  #
  private_key: <%= Rails.root.join 'config', 'id_rsa' %>

  ##
  #
  # Passphrase for private key
  #
  passphrase: openwebslides


  ##
  # GITHUB PROVIDER CONFIGURATION
  #

  ##
  # GitHub OAuth2 credentials
  #
  github_id: <%= ENV['OAUTH_GITHUB_ID'] %>
  github_secret: <%= ENV['OAUTH_GITHUB_SECRET'] %>

  ##
  # GitHub API endpoint
  #
  # https://api.github.com/ for GitHub
  # https://myhost.com/api/v3/ for GitHub Enterprise
  #
  github_api: https://api.github.com/
