##
# Repository path
#
# Local path used for persistent repository storage
repository_path: /srv/repositories

provider:
  ##
  # Data provider type
  #
  # Possible values: ssh, github, local
  #
  # SSH Provider synchronizes the repositories to an external SSH server.
  # GitHub provider synchronizes the repositories to a GitHub organization
  # Local provider does nothing (the repositories are stored locally anyhow)
  #
  type: github

  ##
  # PROVIDER COMMON CONFIGURATION
  #

  ##
  # Provider hostname/IP
  #
  # Hostname of SSH server (for both providers)
  #
  host: github.com

  ##
  # Provider user
  #
  # Login user (for ssh provider)
  # GitHub login user, usually 'git' (for github provider)
  #
  user: git

  ##
  # Path to repository store/organisation
  #
  #
  # Remote path (for ssh provider)
  # Organization name (for github provider)
  #
  path: OpenWebslides-Test

  ##
  # Path to private key
  #
  private_key: <%= Rails.root.join 'config', 'openwebslides.pem' %>

  ##
  #
  # Passphrase for private key
  #
  # passphrase: <%= ENV['KEYFILE_PASSPHRASE'] %>


  ##
  # GITHUB PROVIDER CONFIGURATION
  #

  ##
  # GitHub username
  #
  github_user: OpenWebslides-Platform

  ##
  # GitHub passphrase
  #
  github_passphrase: <%= ENV['GITHUB_PASSPHRASE'] %>

  ##
  # GitHub API endpoint
  #
  # https://api.github.com/ for GitHub
  # https://myhost.com/api/v3/ for GitHub Enterprise
  #
  github_api: https://api.github.com/
