provider:
  ##
  # Data provider type
  #
  # Possible values: ssh, github
  type: ssh

  ##
  # Provider hostname/IP
  #
  host: localhost

  ##
  # Provider port
  #
  # Defaults to 22 for ssh provider and 80 for github
  port: 22

  ##
  # Path to repository store/organisation
  #
  #
  # Possible values: a full path (for ssh provider), organisation name (for github provider)
  path: /srv/openwebslides

  ##
  # GitHub OAuth2 credentials (only for github provider)
  #
  # github_id: <%= ENV['OAUTH_GITHUB_ID'] %>
  # github_secret: <%= ENV['OAUTH_GITHUB_SECRET'] %>

  ##
  # User (only for ssh provider)
  #
  user: openwebslides

  ##
  #
  # Password for user
  #
  # password: openwebslides

  ##
  # Path to private keyfile (only for ssh provider)
  #
  private_key: <%= Rails.root.join 'config', 'private.key' %>
