#%RAML 1.0

traits: !include include/traits.raml

title: Open Webslides
description: This is the documentation of the Open Webslides RESTful API. It is built around the JSON-API v1.0 specification.
version: 1
baseUri: http://localhost:5000/api/
mediaType: application/vnd.api+json
/users:
  displayName: Users
  description: User API
  get:
    is: [paginated]
    description: List of all users
  post:
    description: Create a new user (sign up)
  /{id}:
    uriParameters:
      id:
        type: integer
        description: User ID
    get:
      description: Get user
    patch:
      is: [authenticated]
      description: Update user
    put:
      is: [authenticated]
      description: Update user
    delete:
      is: [authenticated]
      description: Delete user
    /confirm:
      get:
        description: Confirm a user's email address using the `confirmation_token` sent by email
        queryParameters:
          confirmation_token:
            description: Confirmation token sent by email
            required: true
            type: string
            example: WdRB-7YYai9-u-SXZ388
        responses:
          200:
            description: Returned on successful confirmation
          422:
            description: Returned on invalid confirmation code

/decks:
  displayName: Decks
  description: Slidedeck API
  get:
    description: List of all visible decks
  post:
    description: Create a new deck
  /{id}:
    uriParameters:
      id:
        type: integer
        description: Deck ID
    get:
      description: Get deck
    patch:
      description: Update deck
    put:
      description: Update deck
    delete:
      description: Delete deck
/auth:
  displayName: Authentication
  description: Authentication API
  /{provider}:
    get:
      description: OAuth2 redirection URL
    /callback:
      get:
        description: OAuth2 Provider callback URL
  /token:
    post:
      description: Obtain an authentication token
      body:
        application/json:
          type: object
          properties:
            email: string
            password: string
      responses:
        201:
          body:
            application/json:
              type: object
              properties:
                jwt: string
              example:
                { "jwt": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0OTI1OTMxNTcsInN1YiI6MSwidmVyIjoxfQ.cFLhHCC4vFmkGg3FkFaDUA2qnk-RxWkz_pt2SY8VOcQ" }
        403:
          body:
            application/json:
              type: object
              properties:
                error: string
              example: |
               { "error": "Your account has not been activated yet." }
