#%RAML 1.0

traits: !include include/traits.raml

title: Open Webslides
description: This is the documentation of the Open Webslides RESTful API. It is built around the JSON-API v1.0 specification.
version: 1
baseUri: http://localhost:5000/api/
mediaType: application/vnd.api+json
/users:
  displayName: Users
  description: User API
  get:
    is: [paginated]
    description: List of all users
  post:
    description: Create a new user (sign up)
  /{id}:
    uriParameters:
      id:
        type: integer
        description: User ID
    get:
      description: Get user
    patch:
      is: [authenticated]
      description: Update user
    put:
      is: [authenticated]
      description: Update user
    delete:
      is: [authenticated]
      description: Delete user

/decks:
  displayName: Decks
  description: Slidedeck API
  get:
    description: List of all visible decks
  post:
    description: Create a new deck
  /{id}:
    uriParameters:
      id:
        type: integer
        description: Deck ID
    get:
      description: Get deck
    patch:
      description: Update deck
    put:
      description: Update deck
    delete:
      description: Delete deck

/confirmation:
  displayName: Confirmation
  description: Email confirmation API
  post:
    description: Confirm a user's email address using the `confirmation_token` sent by email
    body:
      application/vnd.api+json:
        type: object
        properties:
          data:
            type: object
            properties:
              type:
                description: Should be set to `confirmations`
                type: string
              attributes:
                type: object
                properties:
                  confirmation-token:
                    description: Confirmation token sent by email
                    type: string
                    example: SmiSe22FipwyyPY5Ljjk
        example: |
          {
            "data": {
                "type": "confirmations",
                "attributes" : {
                    "confirmation-token": "SmiSe22FipwyyPY5Ljjk"
                }
            }
          }
    responses:
      204:
        description: Returned on successful confirmation
      400:
        description: Returned on error

/token:
  displayName: Tokens
  description: Authentication API
  post:
    description: Obtain an authentication token
    body:
      application/vnd.api+json:
        type: object
        properties:
          data:
            type: object
            properties:
              email: string
              password: string
    responses:
      204:
        description: Returned on successful authentication
        headers:
          Authorization:
            description: JSON Web Token needed to authenticate (bearer token format)
            example: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0OTI1OTMxNTcsInN1YiI6MSwidmVyIjoxfQ.cFLhHCC4vFmkGg3FkFaDUA2qnk-RxWkz_pt2SY8VOcQ
      401:
        description: Returned on incorrect email or password
      403:
        description: Returned on account not activated yet
  delete:
    is: [authenticated]
    description: Invalidate all tokens
    responses:
      204:
        description: Returned on successful token invalidation
        headers:
      401:
        description: Returned on incorrect token

/auth:
  displayName: Authentication
  description: Authentication API
  /{provider}:
    get:
      description: OAuth2 redirection URL
    /callback:
      get:
        description: OAuth2 Provider callback URL
