// flow-typed signature: ed16b215bc57b2e104d21cca8a897b48
// flow-typed version: <<STUB>>/flowtype_v^2.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flowtype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flowtype' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'flowtype/index' {
  declare module.exports: $Exports<'flowtype'>;
}
declare module 'flowtype/index.js' {
  declare module.exports: $Exports<'flowtype'>;
}
