// flow-typed signature: 13a990f6e5ed2dc8d2060f9f186499bc
// flow-typed version: <<STUB>>/i18next-resource-store-loader_v^0.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-resource-store-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-resource-store-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'i18next-resource-store-loader/index' {
  declare module.exports: $Exports<'i18next-resource-store-loader'>;
}
declare module 'i18next-resource-store-loader/index.js' {
  declare module.exports: $Exports<'i18next-resource-store-loader'>;
}
