// flow-typed signature: a6b345c57c7585bdce64655175f7a875
// flow-typed version: <<STUB>>/ows-convert_v^0.0.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ows-convert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ows-convert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ows-convert/dist/ows-convert' {
  declare module.exports: any;
}

declare module 'ows-convert/dist/ows-convert.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ows-convert/dist/ows-convert.js' {
  declare module.exports: $Exports<'ows-convert/dist/ows-convert'>;
}
declare module 'ows-convert/dist/ows-convert.min.js' {
  declare module.exports: $Exports<'ows-convert/dist/ows-convert.min'>;
}
