// flow-typed signature: 4239985a21a34b1fc7f836e40df73c65
// flow-typed version: <<STUB>>/raml2html-default-theme_v^2.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raml2html-default-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raml2html-default-theme' {
  declare module.exports: any;
}
