// flow-typed signature: b5022c3fa070fc8ebe00f33e48876086
// flow-typed version: <<STUB>>/raml2html_v^6.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raml2html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raml2html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'raml2html/index' {
  declare module.exports: $Exports<'raml2html'>;
}
declare module 'raml2html/index.js' {
  declare module.exports: $Exports<'raml2html'>;
}
