// flow-typed signature: ee135e68c1885407e5c7bf12b74d7969
// flow-typed version: <<STUB>>/react-debounce-render_v^0.0.11/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-debounce-render'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-debounce-render' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-debounce-render/e2e/src/App' {
  declare module.exports: any;
}

declare module 'react-debounce-render/e2e/src/App.test' {
  declare module.exports: any;
}

declare module 'react-debounce-render/e2e/src/DisplayCount' {
  declare module.exports: any;
}

declare module 'react-debounce-render/e2e/src/index' {
  declare module.exports: any;
}

declare module 'react-debounce-render/e2e/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module 'react-debounce-render/lib/index' {
  declare module.exports: any;
}

declare module 'react-debounce-render/src/index' {
  declare module.exports: any;
}

declare module 'react-debounce-render/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-debounce-render/e2e/src/App.js' {
  declare module.exports: $Exports<'react-debounce-render/e2e/src/App'>;
}
declare module 'react-debounce-render/e2e/src/App.test.js' {
  declare module.exports: $Exports<'react-debounce-render/e2e/src/App.test'>;
}
declare module 'react-debounce-render/e2e/src/DisplayCount.js' {
  declare module.exports: $Exports<'react-debounce-render/e2e/src/DisplayCount'>;
}
declare module 'react-debounce-render/e2e/src/index.js' {
  declare module.exports: $Exports<'react-debounce-render/e2e/src/index'>;
}
declare module 'react-debounce-render/e2e/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'react-debounce-render/e2e/src/registerServiceWorker'>;
}
declare module 'react-debounce-render/lib/index.js' {
  declare module.exports: $Exports<'react-debounce-render/lib/index'>;
}
declare module 'react-debounce-render/src/index.js' {
  declare module.exports: $Exports<'react-debounce-render/src/index'>;
}
declare module 'react-debounce-render/webpack.config.js' {
  declare module.exports: $Exports<'react-debounce-render/webpack.config'>;
}
