// flow-typed signature: bfc0ff7818440bf86dd0f4521e5c6a9d
// flow-typed version: <<STUB>>/sane-email-validation_v^1.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sane-email-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sane-email-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sane-email-validation/index' {
  declare module.exports: $Exports<'sane-email-validation'>;
}
declare module 'sane-email-validation/index.js' {
  declare module.exports: $Exports<'sane-email-validation'>;
}
