#%RAML 1.0

filtered:
  queryParameters:
    filter[attribute]?:
      description: Returns results filtered by `attribute`.
      enum: <<values>>
paginated:
  queryParameters:
    offset?:
      description: Returns results based on an `offset` from the beginning of the resultset.
      type: integer
      default: 0
    limit?:
      description: Imposes limits on returned results.
      type: integer
authenticated:
  headers:
    Authorization:
      description: JSON Web Token needed to authenticate (bearer token format)
      example: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0OTI1OTMxNTcsInN1YiI6MSwidmVyIjoxfQ.cFLhHCC4vFmkGg3FkFaDUA2qnk-RxWkz_pt2SY8VOcQ
